// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/conf"
	"app/domains/account"
	"app/domains/audio"
	"app/sql/db"
	"github.com/go-chi/jwtauth"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func controllers(config *conf.Config, jwtAuth *jwtauth.JWTAuth, queries *db.Queries) (reqControllers, error) {
	authService := account.NewAuthService(jwtAuth)
	accountRepo := account.NewAccountRepo(queries)
	accountService := account.NewAccountService(accountRepo, authService)
	authController := account.NewAuthController(config, jwtAuth, authService, accountService)
	accountController := account.NewAccountController(accountService)
	audioController := audio.NewAudioController(authService)
	mainReqControllers := newReqControllers(authController, accountController, audioController)
	return mainReqControllers, nil
}

// wire.go:

type reqControllers struct {
	AuthC  account.AuthController
	AccC   account.AccountController
	AudioC audio.AudioController
}

func newReqControllers(
	authC account.AuthController,
	accC account.AccountController,
	audioC audio.AudioController,
) reqControllers {
	return reqControllers{
		AuthC:  authC,
		AccC:   accC,
		AudioC: audioC,
	}
}
